### ISSUE TITLE
camera extrinsics across frames

### ISSUE THREAD

**Issue by davidsonic** [facebookresearch/Aria_data_tools#11]
Hi, I noticed that the documentation only shows extracting camera extrinsics at the first frame:

``
>>> vrs_data_provider.readFirstConfigurationRecord(slam_left_camera_stream_id)
True
>>> vrs_data_provider.loadDeviceModel()
True
>>> device_model = vrs_data_provider.getDeviceModel()
``

I also looked at the metadata.json extracted from vrs. It seems there's no calibrated extrinsics per-frame. Is this expected? I thought that camera intrinsics is shared across stream but that camera extrinsics should vary with frame?

**Comment by zhaoyang-lv** [comment]
We did not release the online calibration information. You can assume the calibrated extrinsics is shared across the video as well.

**Comment by davidsonic** [comment]
Thanks for the confirmation! What about the trajectory.csv file under location folder? I learned from [doc](https://facebookresearch.github.io/Aria_data_tools/docs/pilotdata/location-output/) that it records left IMU's position and rotation. Then one should be able to convert it to the coordinate frame of rgb?

**Comment by zhaoyang-lv** [comment]
The trajectory.csv is the trajectory of device with device origin at left IMU. To get the rgb frame, you will read the trajectory by rgb timestamp, and transform it from left imu to rgb camera position. 

There are some example codes in the visualization tool when visualizing all three camera positions across time.

**Comment by davidsonic** [comment]
Thanks for the clarification! Closing this issue.
