### ISSUE TITLE
Bindings for VRS creation?

### ISSUE THREAD

**Issue by jonathanzhang99** [facebookresearch/Aria_data_tools#13]
Are there plans to include python bindings to write vrs files from raw jpeg/mp4/pose information in addition to reading? This could be very useful for us!

**Comment by zhaoyang-lv** [comment]
Not plan yet on this. We will keep it tracked as a feature request. I think it might be more actionable to keep track of it (with python bindings) as a feature request for VRS tool.

**Comment by SeaOtocinclus** [comment]
@jonathanzhang99  See the last commit, don't hesitate to sync back. I left some code undone to be used as tutorial ;-)

**Comment by jonathanzhang99** [comment]
@SeaOtocinclus took a look at the update – thank you for the work! Unfortunately for our particular use, it would be difficult to incorporate C++ into our workflow. Is there a way we could build out pybind bindings to call these functions from python?

**Comment by SeaOtocinclus** [comment]
Adding C++ python bindings is doable.
Addition here was mainly to demonstrate feasibility, we can now iterate from there.

**Comment by jonathanzhang99** [comment]
Gotcha! Thanks for that :) Do you guys have a timeline for python bindings?

**Comment by SeaOtocinclus** [comment]
Feature is now implemented.
It was a please to collaborate with you. Thx @jonathanzhang99 & @jaisanliang, team work make dream work!
