### ISSUE TITLE
Parameters for camera-rgb

### ISSUE THREAD

**Issue by Davidyao99** [facebookresearch/Aria_data_tools#14]
I used vrs to extract all the metadata and images from the aria sample dataset. I managed to find the calibration parameters used for the camera-rgb in the metadata json. However, I cannot find documentation for what these parameters represent? It seems to be an array of 15 numbers as shown below:
`\"Params\":[1217.85111143048,1456.022964240926,1445.73331423538,0.3877090025533652,-0.3156133839689442,-0.3434984955068093,1.856587420098875,-2.179937222100279,0.7713834762565884,-0.0002747018833370422,0.0005228973690976568,0.0001348840117906014,-8.482198309822946e-05,-0.0009420014144244382,-0.0001276837565837671]}`
Any idea what these numbers represent? Are they values in the intrinsic matrix? Thank you!

**Comment by zhaoyang-lv** [comment]
This is the camera intrinsics for the rgb camera. See documentation here: https://github.com/facebookresearch/Aria_data_tools/tree/main/src/sensors/models#intrinsics

The parameters are the raw (un-resized) calibration parameters for FisheyeRadTanThinPrism model. 

If you want an implementation reference how to parse this, you can find it here: https://github.com/facebookresearch/Aria_data_tools/blob/6f7fd59014df341e94e5b141846c6327ccf812ec/src/sensors/models/DeviceModel.cpp#L220

**Comment by Davidyao99** [comment]
I see, thank you! Is there a function somewhere to undistort the whole image back to one seen from a pinhole camera?

**Comment by zhaoyang-lv** [comment]
We have not added the function specifically for undistortion. Will track this feature in the near future. You can customize this process with the ray unprojection to form a image plane and use projection function to a pinhole camera you'd like to use.

**Comment by Davidyao99** [comment]
I see. For the projection/unprojection function, is the origin of the 2D image coordinates at the bottom left of the image?

**Comment by zhaoyang-lv** [comment]
pixel origin is the upper-left.

**Comment by Davidyao99** [comment]
I see, thank you!

**Comment by Davidyao99** [comment]
I tried what you suggested and remapped the distorted image to a new image using the projection vector. This is what I got after the remapping. Does the new undistorted image look right? Sry I am new to fish eye lens.
![image](https://user-images.githubusercontent.com/52120948/191377607-821d354a-f724-44fd-8ce0-4e5ad3a96029.png)
The image on the left is the remapped, undistorted image. Image on the right is the original.

**Comment by zhaoyang-lv** [comment]
No, the image does not look right to me. 

Here is one example I got from a view similar to yours (non-rotated), use the same focal length and principle points (extracted from the first three element of fisheye camera parameters). 
![rectified_example](https://user-images.githubusercontent.com/57548912/191614889-28594c07-7b7a-436d-adbe-00ce29ff8f26.jpg)

Just to double check a few details in case you miss it. 
1) If you try to get params from VRS, the default VRS calibration parameters for RGB camera serve for the factory image size 2880x2880. You will need to downscale it properly to the image size 1408x1408. Here is function that does this job: https://github.com/facebookresearch/Aria_data_tools/blob/6f7fd59014df341e94e5b141846c6327ccf812ec/src/sensors/models/DeviceModel.cpp#L530

2) Operate on the raw image (not the rotated as illustrated here).

**Comment by Davidyao99** [comment]
I was trying to make this work in python and remapped the image using the project/unproject function. It seems like the tryCropAndScaleCameraCalibration function is not bound in Python. Should I be doing all these using the C++ version instead?

**Comment by zhaoyang-lv** [comment]
Sorry that a few utility function on our side in python is missing. We need to fix this.  

Here is one rough workflow you can do in python

1. read the calibration model for rgb 
2. rescale it appropriately according to its physical image size (we should have supported it, hopefully soon). 
3. create pixel map using a pinhole camera model  
4. unprojected rays from your pin hole camera model and get the ray intersection points with target image plane.
5. get the projected uv map by projecting the ray intersection points using the fisheye camera projection model 
6. acquire the rectified image from the projected uv map using inverse mapping.

**Comment by Davidyao99** [comment]
Thank you so much for the help! I tried to calculate the calibration by following the C++ implementation, and it seems to be working. 
![image](https://user-images.githubusercontent.com/52120948/191643923-0d655d8a-fe37-453b-a0d2-542ab921e6c7.png)

One last thing I wanted to ask is about this particular line:
[`const double halfCroppedSize = (nativeResolution - newWidth * rescaleFactor) / 2.0;`.](https://github.com/facebookresearch/Aria_data_tools/blob/6f7fd59014df341e94e5b141846c6327ccf812ec/src/sensors/models/DeviceModel.cpp#L530:~:text=const%20double%20halfCroppedSize%20%3D%20(nativeResolution%20%2D%20newWidth%20*%20rescaleFactor)%20/%202.0%3B)

May I ask why is this step necessary? Why can't we just take principalpointx /= rescaleFactor ? Given that rescale factor is nativeResolution / newWidth, wouldnt the value of halfCroppedSize be close to 0?

**Comment by zhaoyang-lv** [comment]
> May I ask why is this step necessary? 

This is the correct way, that matches exactly on how the image was produced on the sensor level. Simply scale it will create a few pixels off.

**Comment by zhaoyang-lv** [comment]
Closing it now since we have solved the problem.

**Comment by Davidyao99** [comment]
Yes sure, thank you so much for your help!!! Awesome project ;)
