### ISSUE TITLE
Difficulty with undistortion continued...

### ISSUE THREAD

**Issue by Davidyao99** [facebookresearch/Aria_data_tools#15]
So sorry for reopening this [issue](https://github.com/facebookresearch/Aria_data_tools/issues/14) again, but I am working on the undistorted images and I am having strange errors. This made me reevaluate my undistorted images and I am not so certain now if I have done it the right way.
![image](https://user-images.githubusercontent.com/52120948/192846226-77bb2df1-69d4-4210-941a-e09a6ee184fd.png)
This is one of the example undistorted image that I achieved. The file name is 214-1-01938-476.517.jpg. I feel like the top right corner of the image still seems to be stretched. I am not sure how to test if my undistortion is right besides looking at it visually.

The following is my undistortion code, and the params I am using from the metadata extracted using vrs:

`{"Calibrated":true,"Label":"camera-rgb","Projection":{"Description":"see FisheyeRadTanThinPrism.h","Name":"FisheyeRadTanThinPrism","Params":[1217.85111143048,1456.022964240926,1445.73331423538,0.3877090025533652,-0.3156133839689442`

````
scale = math.floor(2880/1408)
focal_len = 1217.85111143048 / scale
halfCroppedSize = (2880 - 1408 * scale) / 2.0
p_x = (1456.022964240926  - halfCroppedSize) / scale
p_y = (1445.73331423538- halfCroppedSize) / scale
intrinsic_matrix = [[focal_len, 0, p_x],
                    [0, focal_len, p_y],
                    [0 ,0 ,1]]
intrinsic_matrix_inv = np.linalg.inv(intrinsic_matrix) # calculating inverse intrinsic matrix

x_map = np.zeros((1408, 1408), dtype=np.float32)
y_map = np.zeros((1408, 1408), dtype=np.float32)

undistorted_img = np.zeros((1408, 1408,3))
for x in range(1408):
    for y in range(1408):
        world_coords = intrinsic_matrix_inv @ np.array([x, y, 1]) # unproject from pinhole image to world coordinate
        p = device_model.getCameraCalib('camera-rgb').projectionModel.project(world_coords) # project world coordinate to fisheye image
        x_map[y][x] = p[0]
        y_map[y][x] = p[1]

img1 = cv2.imread(file)
dst = cv2.remap(img1, x_map, y_map, cv2.INTER_CUBIC)
cv2.imwrite(dst_path, dst)

**Comment by SeaOtocinclus** [comment]
Best is to use the intrinsic and camera parameter value return by the device_model (the accurate resizing function are implemented for you). Since here we just don't have a naive rescaling.
But else your code to manipulate pixel camera rays from one camera representation to another is looking good (as you can see, straight lines are straight and that's a good sign!)
