### ISSUE TITLE
Definition of Device Frame for Aria Glasses

### ISSUE THREAD

**Issue by akashsharma02** [facebookresearch/Aria_data_tools#17]
Hi, 

Thanks for releasing the dataset and the tools to work with the dataset. 

![image](https://user-images.githubusercontent.com/6978474/194107110-6b240c9b-7fab-489a-9f49-708974c3cb90.png)

In the above figure, the device frame that is referenced in the ImuCalibration as well as CameraCalibrations is not defined. Could someone please update the figure or let me know where exactly it is located?

**Comment by zhaoyang-lv** [comment]
We did not define a device frame in the released conventions. Trajectory released is saved by a series of timestamped transformations of the Project Aria device's left IMU relative to the world coordinates (frames).  What do you need it for?

**Comment by akashsharma02** [comment]
I was just curious because the nominal rate of left IMU (1202-2) is 800Hz, and the numbering for the SLAM (left-right) cameras and IMU (left-right) are not consistent.

**Comment by zhaoyang-lv** [comment]
That's at implementation level. At the interface level, we did not expose it. Why will you need it explicitly?
