### ISSUE TITLE
Clarification on sensor parameters from VRS

### ISSUE THREAD

**Issue by Davidyao99** [facebookresearch/Aria_data_tools#19]
Hi, I am trying to use the trajectory and camera parameters extracted using VRS to visualize point clouds and epipolar geometry. However, there seem to be errors in the final visualization and I am hoping to clarify my understanding. I am querying the position and orientation of the left-imu camera in the provided trajectory.csv file using the RGB-camera timestamp. For the sample dataset for everyday_activity, I notice that the timestamps for the RGB camera start a few seconds before the first entry of the trajectory.csv. Is this supposed to happen? Do I have to take this offset into account? Thank you!

**Comment by SeaOtocinclus** [comment]
It is expected that some frames will not have corresponding poses in the start of the sequence (some frames at the start are used as initialization and so does not have final poses information).
-> If you use the data_provider, you should have all information in sync (as they are displayed in the viewers) (Frames + camera poses)

**Comment by Davidyao99** [comment]
I see. Thank you for your response! I was wondering what is the margin for error for the trajectory data? I am using the trajectory data to calculate camera poses to calculate epipolar geometry for rgb-camera frames. Is using the trajectory provided at the timestamp for each rgb-camera frame accurate enough for this task?

**Comment by zhaoyang-lv** [comment]
> Is using the trajectory provided at the timestamp for each rgb-camera frame accurate enough for this task

We don't have absolute ground truth set up for this dataset, but from our quality analysis, the answer is "yes".
