### ISSUE TITLE
Visualize in docker

### ISSUE THREAD

**Issue by RBKing20** [facebookresearch/Aria_data_tools#22]
I want to run visualization tools in docker container, but encountered the problem of displaying Pangolin. I followed this [document](https://facebookresearch.github.io/Aria_data_tools/docs/Install/) .
`$ sudo xhost +`
`$ docker run -it -e DISPLAY  --volume <your_local_data>:/data --network=host aria_data_tools:latest`
I would like to ask if there are other operations needed because I am not familiar with docker.
```
root@docker-desktop:/opt/aria_data_tools/src/visualization# python3 main.py --vrs_path /data/everyday_activity/recording_1/recording.vrs 
Loading poses file from /data/everyday_activity/recording_1/location/trajectory.csv
Loaded 119198 poses
Loading eye tracking file from /data/everyday_activity/recording_1/eyetracking/et_in_rgb_stream.csv
Loaded 1204 eye tracking points
Loading speech2text file from /data/everyday_activity/recording_1/speech2text/speech_aria_domain.csv
Loaded 250 speech2text points
Opened the VRS file successfully
Eye stream player doesn't exist, cannot update camera calibration
Start AriaViewer0!
error: XDG_RUNTIME_DIR not set in the environment.
Traceback (most recent call last):
  File "main.py", line 78, in <module>
    viewer.run()
RuntimeError: Pangolin X11: Failed to open X display
^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt:
```

**Comment by zackeryzhou** [comment]
May I know how you solved the problem? I had the same one. Thanks.

**Comment by zackeryzhou** [comment]
In the docker container, I took a look at the output of `echo $DISPLAY`, it returns `docker.for.mac.host.internal:0`. Therefore, I also tried `docker run -it -e DISPLAY=docker.for.mac.host.internal:0 --volume <your_local_data>:/data --network=host aria_data_tools:latest` to start a new container. But it ended up with the same error like yours.
