### ISSUE TITLE
How to use AriaViewer with Python?

### ISSUE THREAD

**Issue by maria-t** [facebookresearch/Aria_data_tools#33]
Hi! 

I am trying to visualize sequences with AriaViewer in Python but I get that there is no `main.py` file.

Am I doing something wrong with my python setup? Thank you!

**Comment by SeaOtocinclus** [comment]
Hello @maria-t ,
I assume you are trying to use this documentation to run our python visualizers: https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/visualization/visualization_python

We are using short names that refers to main in python files packaged with projectaria_tools, you can find the mapping here https://github.com/facebookresearch/projectaria_tools/blob/main/setup.py#L201

If you want to use the C++ binaries (referred here https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/visualization/visualization_cpp#run-aria-viewer), we are not packaging them but you can build them following the instruction shared here https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/installation/installation_cpp

**Comment by maria-t** [comment]
Hi again! 
No, I am using the documentation [here](https://facebookresearch.github.io/Aria_data_tools/docs/howto/visualizing/), since I am trying to visualize sequences from the Pilot dataset. 

In the meantime, I managed to run the visualization tool in C++, but then I have the problem that the eye-tracking red cross, trajectory and speechtotext paths are not working.

**Comment by SeaOtocinclus** [comment]
@maria-t the dataset has been updated and shared here 
https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_everyday_activities_dataset

You can also use the new visualizer developed for it https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_everyday_activities_dataset/aea_visualizers#python-visualizer

**Comment by SeaOtocinclus** [comment]
Hello @maria-t, please do find the official new re-release of the dataset here https://www.projectaria.com/datasets/aea/

**Comment by maria-t** [comment]
Great, thank you!
