### ISSUE TITLE
PyPi support

### ISSUE THREAD

**Issue by jonathanzhang99** [facebookresearch/Aria_data_tools#7]
Hi! Are you guys considering uploading and supporting this library on pypi in the near future?

**Comment by fskarakas** [comment]
@jonathanzhang99 yes it is part of our roadmap and any updates regarding the release will be shared in the project page.

**Comment by encouver** [comment]
I see that the library is available at: 

https://pypi.org/project/projectaria-tools/

After trying to install it:

pip install projectaria-tools

I get this error:

ERROR: Could not find a version that satisfies the requirement projectaria-tools (from versions: none)
ERROR: No matching distribution found for projectaria-tools

**Comment by SeaOtocinclus** [comment]
@encouver Do you still encounter the same error?
What is your platform?

**Comment by encouver** [comment]
> @encouver Do you still encounter the same error? What is your platform?

Yes, the error still persist. 

My platform:

Windows 10 
Conda environment
Python 3.9.16
pip 23.0.1
conda 23.3.1



Let me know if that helps or if you need additional information.

**Comment by SeaOtocinclus** [comment]
@encouver  We are supporting only Mac and Linux platforms.
- VRS a dependency we are using is not yet easy to build on windows.

Please use a docker container or a virtual machine or another way to get a supported platform. Thank you

**Comment by sihatafnan** [comment]
@SeaOtocinclus I am using MacBook pro, macOS Sequoia 15.2. I am getting the same error

**Comment by binhphan77373** [comment]
I see that the library is available at:

https://pypi.org/project/projectaria-client-sdk/

After trying to install it:

pip install projectaria-client-sdk

I get this error:

ERROR: Could not find a version that satisfies the requirement projectaria-client-sdk (from versions: none)
ERROR: No matching distribution found for projectaria-client-sdk

My platform: Jetson Orin NX
