### ISSUE TITLE
Unable to open SLAM images from Desktop Activity Sample set

### ISSUE THREAD

**Issue by jonathanzhang99** [facebookresearch/Aria_data_tools#8]
I am using the desktop activity dataset provided on the [Aria Dataset](https://about.facebook.com/realitylabs/projectaria/datasets/)

When I try to open the SLAM left and right cameras using the following snippet:
```python
vrs_data_provider = pyark.datatools.dataprovider.AriaVrsDataProvider()
vrs_data_provider.openFile("desktop_activity/aria_recording.vrs")

vrs_data_provider.setSlamLeftCameraPlayer()
slam_left_player = vrs_data_provider.getSlamLeftCameraPlayer()

vrs_data_provider.readFirstConfigurationRecord(slam_left_player.getStreamId())

vrs_data_provider.readDataRecordByTime(slam_left_player.getStreamId(), 0)
data = slam_left_player.getData()
```
data is `None` and i get the following Warning:
```
[ContentBlockReader][WARNING]: Can't define the image block format for Camera Data (SLAM) #2 to read this image block with DataLayout. This might be happening, because the image format is defined in a configuration record using datalayout conventions, but no configuration record was read prior to reading this Data record.
```
This prevents me from accessing the images directly unless I unpack them manually using the `vrs` tool. Any idea why this might be happening?

Also, are there any plans to expose the `getImageSensorPlayer` API on the python library to load arbitrary vrs files? (including the `multiview_recording.vrs` included in the sample dataset?)

**Comment by SeaOtocinclus** [comment]
Hi @jonathanzhang99 
Can you try to run this sample on the file you are trying to open and let us know what is happening:
- https://github.com/facebookresearch/Aria_data_tools/blob/main/src/visualization/main.py

**Comment by jonathanzhang99** [comment]
Ah apologies – this is for the desktop activity dataset. I will update the title

**Comment by fskarakas** [comment]
@jonathanzhang99 SLAM camera images in Aria recordings of desktop activities dataset are not JPEG compressed but are in RAW format. Changes needed to load these records together with a dedicated viewer for the desktop activity dataset will be added soon.

**Comment by jonathanzhang99** [comment]
Ah gotcha – thank you for the update.
