### ISSUE TITLE
some docker commands seems does not work well

### ISSUE THREAD

**Issue by Jiakaii** [facebookresearch/Aria_data_tools#9]
To enable visualization, the documentation says:

```docker run -it -e DISPLAY  --volume /data:/data --network=host aria_data_tools_base:latest```

But it seems the repo name should be `aria_data_tools` instead of `aria_data_tools_base`

**Comment by SeaOtocinclus** [comment]
Thank you @Jiakaii for reporting the issue and how to fix it. We updated the doc.
